"""add_payment_accounts_table

Revision ID: 2de9ab82f7e1
Revises: a429e3dbeb86
Create Date: 2025-11-19 00:57:25.599478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de9ab82f7e1'
down_revision = 'a429e3dbeb86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('UPI', 'BANK', 'CRYPTO', name='paymentaccounttype'), nullable=False),
    sa.Column('identifier_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='paymentaccountstatus'), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_accounts_account_type'), 'payment_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_payment_accounts_id'), 'payment_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_payment_accounts_is_active'), 'payment_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_payment_accounts_status'), 'payment_accounts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_accounts_status'), table_name='payment_accounts')
    op.drop_index(op.f('ix_payment_accounts_is_active'), table_name='payment_accounts')
    op.drop_index(op.f('ix_payment_accounts_id'), table_name='payment_accounts')
    op.drop_index(op.f('ix_payment_accounts_account_type'), table_name='payment_accounts')
    op.drop_table('payment_accounts')
    # ### end Alembic commands ###

