"""Initial migration

Revision ID: a429e3dbeb86
Revises: 
Create Date: 2025-11-18 00:22:56.673523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a429e3dbeb86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('EMAIL', 'SMS', 'BLOCKCHAIN', name='ledgersource'), nullable=False),
    sa.Column('method', sa.Enum('UPI', 'BANK', 'CRYPTO', name='ledgermethod'), nullable=False),
    sa.Column('utr_or_hash', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_ledger_id'), 'incoming_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_incoming_ledger_matched'), 'incoming_ledger', ['matched'], unique=False)
    op.create_index(op.f('ix_incoming_ledger_utr_or_hash'), 'incoming_ledger', ['utr_or_hash'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('UPI', 'BANK', 'CRYPTO', name='depositmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('utr_or_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'FLAGGED', name='depositstatus'), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_id'), 'deposits', ['id'], unique=False)
    op.create_index(op.f('ix_deposits_status'), 'deposits', ['status'], unique=False)
    op.create_index(op.f('ix_deposits_utr_or_hash'), 'deposits', ['utr_or_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deposits_utr_or_hash'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_status'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_id'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_incoming_ledger_utr_or_hash'), table_name='incoming_ledger')
    op.drop_index(op.f('ix_incoming_ledger_matched'), table_name='incoming_ledger')
    op.drop_index(op.f('ix_incoming_ledger_id'), table_name='incoming_ledger')
    op.drop_table('incoming_ledger')
    # ### end Alembic commands ###

